### ISSUE TITLE
Better SSHKey fingerprint handling

### ISSUE THREAD

**Issue by gicmo** [G-Node/gin-auth#84]
Properly deal with the `SHA256:` prefix:

``` diff
diff --git a/web/account.go b/web/account.go
index a2c5dfd..64af28c 100644
--- a/web/account.go
+++ b/web/account.go
@@ -11,6 +11,7 @@ package web
 import (
        "encoding/json"
        "net/http"
+       "strings"

        "github.com/G-Node/gin-auth/conf"
        "github.com/G-Node/gin-auth/data"
@@ -277,6 +278,11 @@ func ListAccountKeys(w http.ResponseWriter, r *http.Request) {
 // GetKey returns a single ssh key identified by its fingerprint as JSON.
 func GetKey(w http.ResponseWriter, r *http.Request) {
        fingerprint := mux.Vars(r)["fingerprint"]
+
+       if strings.HasPrefix(fingerprint, "SHA256:") {
+               fingerprint = fingerprint[7:]
+       }
+
        key, ok := data.GetSSHKey(fingerprint)
        if !ok {
                PrintErrorJSON(w, r, "The requested key does not exist", http.StatusNotFound)
```

Also our current handling of the `/` in the fingerprint seems awkward.

**Comment by gicmo** [comment]
Base64 encoding the fingerprint, or using POST or url encoding all might be better then just `/` -> `_`, which is what we currently do.

**Comment by mpsonntag** [comment]
A suggestion for different handling:
- save only the plain, unencoded SHA256 fingerprint when the key is created in the database.
- when fetching or deleting a key, only accept SHA256 fingerprints, return a descriptive error message otherwise.
- remove fingerprint from hierarchical part of the URL and accept fingerprints only as URL encoded URL query.
